name: Execute full test run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Install Chrome
      run: browser-actions/setup-chrome@v2
      with:
        chrome-version: 'latest'
    - name: Install ChromeDriver
      run: browser-actions/setup-chromedriver@v2
      with:
        chromedriver-version: 'latest'
    - name: Run maven test
      run: mvn test
